version: '3.8'

services:
  mealsync-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mealsync-master
    ports:
      - "3016:3016"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3016
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - mealsync-network

networks:
  mealsync-network:
    driver: bridge
