name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, main]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: docker build -t mealsync:latest .
    
    - name: run Docker Image
      run: docker compose up -d
    
    - name: Success
      run: echo "âœ… Build successful!"
